image: image: alpine/latest
sources:
- https://git.sr.ht/~tsileo/microblog.pub
packages:
- python3-dev
- python3-pip
- poetry
tasks:
 - tests |
    cd microblog.pub
    poetry install --no-interaction
    poetry run inv lint
    poetry run inv tests
