version: "3"

services:
  server:
    image: microblogpub/microblogpub:latest 
    container_name: microblogpub
    user: 10000:10000
    restart: always
    volumes:
      - ./data:/app/data
      - ./app/static:/app/app/static
    ports:
      - "8000:8000"
