on:
  push:
    branches:    
      - 'v2'
jobs:
  tests:
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: poetry install
    - run: poetry run inv tests
